[fix][broker] EntryFilters fix NoClassDefFoundError due to closed classloader (#22767)
(cherry picked from commit caccd54f2ceabae0b24b8c14df088c94b7a72643)